// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchOperationsForFilter(arg1:main.Filter):Promise<Array<{[key: string]: string}>>;

export function SelectFile():Promise<void>;
